### ISSUE TITLE
Built remix app fails to parse request when running locally or deployed (fly.io)

### ISSUE THREAD

**Issue by swalker326** [mjackson/multipart-parser#12]
I ran into an issue where my built and ran app running locally failed to parse any data from the request. 

Example repo: https://github.com/swalker326/multipart-build-issue

When you run `pnpm dev` everything works as expects and you can see the response data logged in the console. 

When the app is built `pnpm build` and ran `pnpm start` no data is parsed from the request. 

## Dev
![image](https://github.com/user-attachments/assets/2b3eb07d-6c6b-4734-89ad-d1ea71d45d07)

## Build/Start
![image](https://github.com/user-attachments/assets/4041539a-c089-4998-990c-7ea29662634c)

**Comment by Aulos** [comment]
Seems similar to #10 

Are you using `installGlobals`? Try to remove it

**Comment by swalker326** [comment]
> Seems similar to #10 
> 
> 
> 
> Are you using `installGlobals`? Try to remove it

I had read that issue before posting. I'm not using 'installGlobals' just weird that it works correctly when running dev but not build.

**Comment by swalker326** [comment]
Still stuck on this but, troubleshooting (more stabbing in the dark honestly lol)

When i go into my node modules and add a console.log to the `MutlipartPart` constructor and try to look at the `headers.contentDisposition` 

```js
constructor(header, body) {
    console.log(
	    ":::Header",
	    new Headers(new TextDecoder().decode(header)).contentDisposition,
	);
    this.#header = header;
    this.#body = body;
}
```

### Dev

![image](https://github.com/user-attachments/assets/217d7455-60d6-4919-9391-ce9e620a8f3d)


### Built/Start

![image](https://github.com/user-attachments/assets/5569d65f-f88d-4832-95bc-e59146eb4896)

**Comment by mjackson** [comment]
@swalker326 Are you 100% sure you're not using `installGlobals()` anywhere in your built version of the app? Check the built server bundle to be sure.

Also, what version of node are you running?

**Comment by swalker326** [comment]
> @swalker326 Are you 100% sure you're not using `installGlobals()` anywhere in your built version of the app? Check the built server bundle to be sure.
> 
> Also, what version of node are you running?

In the sample project I don't call installGlobals() anywhere. 

using node v22 tried with node v20 also and same results

![image](https://github.com/user-attachments/assets/9429ac88-7ed0-477a-a4c4-4f07c2dfd869)

**Comment by swalker326** [comment]
@jacob-ebey Got me sorted out, the remix-serve CLI is calling `installGlobals`

**Comment by mjackson** [comment]
Ah yeah, we really need to move that into purely a userland concern so we don't do that for you.

I'm going to close since there's nothing for us to do here.
